dryrun: True
include_self: True
include_dependencies: True
include_tooling_and_runtime: False
min_contributions: 1
check_equal_privat_and_public_wallet: False
skip_email: False
btc_per_transaction: 0.000002
contributor_payout_count: 1
total_payout_per_run: 0.000002
email_note: "Fresh OpenCelery Donation"
