
# ./.github/workflows/docker_run.yml
on: [push]

name: Run Docker Image CI
jobs:
build:
runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build from Docker File
              run: ./install_and_build.sh
            - name: Run on own sources
              run: ./protontypes_docker.sh ./
