# ./.github/workflows/docker_run.yml
on: 
    push:
      branches:    
        - master
#on:
#   release:
#      types: [published]

jobs:
  opencelery:
    name: build_and_run
    runs-on: ubuntu-latest
    steps:
      # Check out the repo opencelery is working on
      - uses: actions/checkout@v1
#      - name: Build Container
#        run:  docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t opencelery .
      - name: Pull Last Build from Docker Hub
        run: docker pull opencelery/opencelery      
      - name: Run Container on own sources as input
        run:  docker run --rm \
                --env GITHUB_TOKEN=$GITHUB_TOKEN \
                --env LIBRARIES_IO_TOKEN=$LIBRARIES_IO_TOKEN \
                --env COINBASE_TOKEN=$COINBASE_TOKEN \
                --env COINBASE_SECRET=$COINBASE_SECRET \
                opencelery \
                bash -c 'export PAY=1;python3 celery.py --folder=./' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_IO_TOKEN: ${{ secrets.LIBRARIES_IO_TOKEN }}
          COINBASE_TOKEN: ${{ secrets.COINBASE_TOKEN }}
          COINBASE_SECRET: ${{ secrets.COINBASE_SECRET }}
      
#      - uses: actions/upload-artifact@v1
#        with:
#          name: Billing
#          path: receipt.txt
#      - uses: ammaraskar/sphinx-action@master
#        with:
#          docs-folder: "./docs/"
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#          build-command: "sphinx-build ./sphinx/ ./"
