# ./.github/workflows/docker_run.yml
name: Docker Build and Run

on: push

jobs:
  my-job:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt large secret
        run:  docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t protontypes .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_IO_TOKEN: ${{ secrets.LIBRARIES_IO_TOKEN }}:  


