# ./.github/workflows/continuouscelery.yml
# Use OpenCelery as a simple Github action on your project workflow.
# For configuration create an .opencelery.yml file in your project repo.
name: opencelery
on: 
    push:
      branches:
        - master

jobs:
  opencelery:
    name: opencelery
    runs-on: ubuntu-latest
    steps:
      # Check out the repo opencelery is working on.
      - uses: actions/checkout@v1
      - name: pull opencelery from dockerhub
        run: docker pull opencelery/opencelery
      # Run OpenCelery on the current folder.
      - name: Run OpenCelery on Sources
        run:  > 
                docker run --rm \--env GITHUB_TOKEN=$GITHUB_TOKEN 
                --env LIBRARIES_IO_TOKEN=$LIBRARIES_IO_TOKEN 
                --env COINBASE_TOKEN=$COINBASE_TOKEN 
                --env COINBASE_SECRET=$COINBASE_SECRET
                -v $(pwd):/home/celery/runningrepo/ 
                opencelery/opencelery 
                bash -c 'python3 celery.py --folder=/home/celery/runningrepo/' 
        # Never print
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_IO_TOKEN: ${{ secrets.LIBRARIES_IO_TOKEN }}
          COINBASE_TOKEN: ${{ secrets.COINBASE_TOKEN }}
          COINBASE_SECRET: ${{ secrets.COINBASE_SECRET }}
        # Upload the receipt file to github artifact.
      - uses: actions/upload-artifact@v1
        with:
          name: billing
          path: receipt.txt
