# ./.github/workflows/continuousselery.yml
# Use Openselery as a simple Github action on your project workflow.
# For configuration create an .openselery.yml file in your project repo.
name: openselery
on: 
    push:
      branches:
        - master

jobs:
  openselery:
    name: openselery
    runs-on: ubuntu-latest
    steps:
      # Check out the repo openselery is working on.
      - uses: actions/checkout@v1
      - name: pull openselery from dockerhub
        run: docker pull openselery/openselery
      # Run Openselery on the current folder.
      - name: Run Openselery on Sources
        run:  > 
                docker run --rm \--env GITHUB_TOKEN=$GITHUB_TOKEN 
                --env LIBRARIES_IO_TOKEN=$LIBRARIES_IO_TOKEN 
                --env COINBASE_TOKEN=$COINBASE_TOKEN 
                --env COINBASE_SECRET=$COINBASE_SECRET
                -v $(pwd):/home/selery/runningrepo/ 
                openselery/openselery 
                bash -c 'python3 selery.py --folder=/home/selery/runningrepo/' 
        # Never print
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_IO_TOKEN: ${{ secrets.LIBRARIES_IO_TOKEN }}
          COINBASE_TOKEN: ${{ secrets.COINBASE_TOKEN }}
          COINBASE_SECRET: ${{ secrets.COINBASE_SECRET }}
        # Upload the receipt file to github artifact.
      - uses: actions/upload-artifact@v1
        with:
          name: billing
          path: receipt.txt
